# Generated by Django 6.0.2 on 2026-04-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_knowledgedocument_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cost_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.SmallIntegerField(choices=[(-1, 'Down'), (0, 'None'), (1, 'Up')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_in',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_out',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
