# Generated by Django 6.0.2 on 2026-04-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_cost_usd_message_feedback_message_request_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
